### ISSUE TITLE
Traceback on gat.py

### ISSUE THREAD

**Issue by juba12** [romankh/gsm-assessment-toolkit#6]
Hello, I appreciate your work but when i run ./gat.py on Ubuntu or Kali Linux, i have this problem that i can't solve for now :

Traceback (most recent call last):
  File "./gat.py", line 19, in <module>
    conf = ConfigProvider()
  File "/home/utilisateur/Téléchargements/gsm-assessment-toolkit-master/core/common/config.py", line 36, in __init__
    self.sessions_dir = expanduser(self.get('gat', 'usersessions'))
  File "/home/utilisateur/Téléchargements/gsm-assessment-toolkit-master/core/common/config.py", line 55, in get
    return self.__config.get(section, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'gat'

(I already use gr-gsm, python, pip correctly)

Thank you in advance

**Comment by romankh** [comment]
Hi @juba12,

thank you for reporting, it was a bug in initialization of the default config, introduced by my recent package refactoring. I just committed a quick fix, can you pull the recent changes and drop me a note if this fixes the issue for you ?

**Comment by juba12** [comment]
Good work ! Thank you
